// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkgXh1NPB-M-Gak6eCpdmMJ30ToqI1zh4',
    appId: '1:671655381307:web:bf29b132dc914478af0f1e',
    messagingSenderId: '671655381307',
    projectId: 'lingo-sign',
    authDomain: 'lingo-sign.firebaseapp.com',
    storageBucket: 'lingo-sign.firebasestorage.app',
    measurementId: 'G-1RFXR7GH97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9A3iqBQV9U19r2xqX2h8LAJT14pquYpk',
    appId: '1:671655381307:android:105169bc71836464af0f1e',
    messagingSenderId: '671655381307',
    projectId: 'lingo-sign',
    storageBucket: 'lingo-sign.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATNE_xkaAIIVq11gog45ivEbim6EO7qF8',
    appId: '1:671655381307:ios:8505b0ef68afd103af0f1e',
    messagingSenderId: '671655381307',
    projectId: 'lingo-sign',
    storageBucket: 'lingo-sign.firebasestorage.app',
    androidClientId: '671655381307-d7elnegikjb2nif33q0o3pnk1p832dr0.apps.googleusercontent.com',
    iosClientId: '671655381307-2sv66omrnm8on7aneoaltilb9fr1hjc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.lingoSign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATNE_xkaAIIVq11gog45ivEbim6EO7qF8',
    appId: '1:671655381307:ios:8505b0ef68afd103af0f1e',
    messagingSenderId: '671655381307',
    projectId: 'lingo-sign',
    storageBucket: 'lingo-sign.firebasestorage.app',
    androidClientId: '671655381307-d7elnegikjb2nif33q0o3pnk1p832dr0.apps.googleusercontent.com',
    iosClientId: '671655381307-2sv66omrnm8on7aneoaltilb9fr1hjc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.lingoSign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkgXh1NPB-M-Gak6eCpdmMJ30ToqI1zh4',
    appId: '1:671655381307:web:fe887b7b7a4f56b3af0f1e',
    messagingSenderId: '671655381307',
    projectId: 'lingo-sign',
    authDomain: 'lingo-sign.firebaseapp.com',
    storageBucket: 'lingo-sign.firebasestorage.app',
    measurementId: 'G-8MS04LYPDR',
  );

}